### ISSUE TITLE
Adjust the go module name regarding the repo name update

### ISSUE THREAD

**Issue by cool-develope** [Lagrange-Labs/lsc-node#622]
## Tasks

- [x] Adjust all module names with `lsc-node`
- [x] Tagging the submodules
- [x] Adjust the `go.mod` with the appropriate the submodule versions
- [x] Update the `README`
